name: Flujo de lanzamiento

on:
  push:
    branches:
      - "desarrollo"

jobs:
  release-process:
    name: proceso-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v4

      - name: Verificar palabra clave en el commit
        id: verificar_palabra_clave
        run: |
          if git log -1 --pretty=%B | grep -q "ESTADO_TERMINADA"; then
            echo "clave_encontrada=true" >> $GITHUB_ENV
          else
            echo "clave_encontrada=false" >> $GITHUB_ENV
          fi

      - name: Crear rama release
        if: env.clave_encontrada == 'true'
        run: |
          git checkout -b release
          git push -f -u origin release

      - name: Mezcla desarrollo -> release
        if: env.clave_encontrada == 'true'
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: desarrollo
          target-branch: release

      - name: Configuración de entorno de python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.8'

      - name: Instalación de librerías y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Correr pruebas unitarias
        id: correr-pruebas
        run: python -m unittest discover -s tests -v

      - name: Mezcla release -> main
        if: success()
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: release
          target-branch: main

      - name: Cerrar acción si hay errores
        if: failure()
        run: echo "Las pruebas fallaron, cerrando la acción sin mezclar en main. "